qutip/QuantumToolbox.jl

- docs/src/api.md
- src/QuantumToolbox.jl
- src/quantum_operators.jl
- test/runtests.jl
Support `qeye` which makes the syntax more similar to `QuTiP`.
> add `qeye()=eye()`

- src/QuantumToolbox.jl
- src/progress_bar.jl
- src/time_evolution/mcsolve.jl
- src/time_evolution/mesolve.jl
- src/time_evolution/sesolve.jl
- src/time_evolution/time_evolution.jl
- src/time_evolution/time_evolution_dynamical.jl
This PR introduces the ProgressBar feature, that is currently applied to sesolve and mesolve. The support for mcsolve is still missing, because we have to find a way to support type stable support with Distributed.
> Introduced ProgressBar

- .github/workflows/documentation.yml
This PR introduces the DOCUMENTER_KEY for correctly deploy documentation.
> Fix Documenter key missing

- src/quantum_object.jl
Multiple-dispatch `show()` for different `QuantumObjectType`
> Optimize `show()` for `QuantumObject`

- docs/Project.toml
- docs/src/benchmarks/benchmark_history.md
- docs/src/lowrank.md
This PR fixes the incomplete view of the Benchmark page, and it also replaces the `Plots.jl` package with `CairoMakie.jl` package.
> Fix Benchmark page and replace Plots.jl with CairoMakie.jl

- docs/src/benchmarks/benchmark_history.md
Try to directly embed the benchmark plots inside Documenter.jl code.
> Test the benchmark page with a simple test case

- src/QuantumToolbox.jl
- src/steadystate.jl
- src/time_evolution/time_evolution.jl
I moved the steady state functions to a dedicated file called steadystate.jl to make the code clearer.
> Move all steadystate functions into a dedicated file

- docs/make.jl
This line was removed, probably when resolving a conflict with the formatter. I rewrite this line now.
> Add favicon

- Project.toml
- README.md
- docs/make.jl
- docs/src/benchmarks/benchmark_history.md
- docs/src/index.md
- docs/src/tutorials/logo.md
These changes are needed to keep this repository working on the new organization.
> Changes for move on QuTiP org

- docs/src/tutorials/logo.md
Minor change just to test documentation deployment
> Minor change

- docs/src/api.md
- src/QuantumToolbox.jl
- src/steadystate.jl
- test/steady_state.jl
> ODE-stationary-state solver

- README.md
- docs/src/index.md
Fix the wrong spelling of the word "annihilation".
> Fix typo in comments

- src/time_evolution/mcsolve.jl
- test/time_evolution_and_partial_trace.jl
Last but not least, fixing the type instabilities for `mcsolve`
> Type inference tests mcsolve

- src/correlations.jl
- test/correlations_and_spectrum.jl
With this PR I fix the type instabilities of the `spectrum` function.
> Fix type instabilities for spectrum

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- .github/ISSUE_TEMPLATE/others.yaml
- .github/pull_request_template.md
I just do copy-and-paste from python qutip repo and did some modifications.
> Add templates for submitting issues or PRs

- Project.toml
The type instability with `PresetTimeCallback` in `DiffEqCallbacks v3.8.0` has been solved.
https://github.com/SciML/DiffEqCallbacks.jl/issues/225
https://github.com/SciML/DiffEqCallbacks.jl/pull/230
> Update compat with `DiffEqCallbacks`

- .buildkite/pipeline.yml
close #40 
as title
we should be ready for the buildkite GPU tests (once they finish the setup)
> Update buildkite token

- .github/ISSUE_TEMPLATE/bug_report.yaml
- src/QuantumToolbox.jl
- src/versioninfo.jl
This is just a PR for minor changes. Modify the output of `versioninfo`.
> Fix typo for `versioninfo`

- src/qobj/arithmetic_and_attributes.jl
- src/qobj/quantum_object.jl
- src/utilities.jl
- test/quantum_objects.jl
Remake PR #224 
Also, move some functions to `utilities.jl`
> Fix `ptrace`

- Makefile
This PR add a new command `all` in Makefile in order to run every command.
> Add command `all` to Makefile

- .github/workflows/CI-Julia-nightly.yml
> Remove code quality tests under Julia nightly

- Makefile
As title, this PR modifies `Makefile` to make it more readable.
> modify Makefile

- src/time_evolution/mcsolve.jl
This PR improves the performance of `mcsolve`. This changes the way to compute which collapse operator is acting of the state. To do this, I preallocate the list of hermitian collapse operators $\hat{C}^\dagger \hat{C}$, making much easier to compute $\langle \psi \vert \hat{C}^\dagger \hat{C} \vert \psi \rangle$.
I already see some performance improvement in the benchmarks, and I expect more improvements when the initialization overhead is much less than the integration time.
> Improve mcsolve performance

- src/progress_bar.jl
> Make ProgressBar mutable

- src/time_evolution/mesolve.jl
There was a minor error in the code
> Fix issue in mesolve for nothing c_ops

- docs/src/.vitepress/theme/VersionPicker.vue
This PR tries to fix the VersionPicker (we copied `VersionPicker.vue` from `Lux.jl`)
> Fix VersionPicker

- .github/workflows/CleanPreviewDoc.yml
- docs/src/.vitepress/config.mts
> Fix the location of `versions.js`

- .github/workflows/FixSymbolicLinks.yml
- DeployDocs.yml
> upload ci config to fix symbolic link for Vitepress

- docs/src/index.md
> Fix bad link for API button in home page

- .github/pull_request_template.md
- README.md
- docs/make.jl
- docs/src/resources/contributing.md
> Add contribute documentation page

- docs/src/resources/contributing.md
The Vitepress seems to be not supporting nested lists when there's both ordered and un-ordered lists at the same time.
So I just make it all un-ordered, and also did a few minor changes.
> Fix contributing page

- docs/src/resources/bibliography.bib
The original links for the book by Nielsen and Chuang somehow links to Amazon.com ...
Fixed in this PR
> Fix incorrect bibliography

- docs/src/.vitepress/theme/VersionPicker.vue
> Remove extra `/` in documentation URLs

- docs/src/.vitepress/config.mts
I don't know why the favicon sometimes show up, sometimes disappeared
I just upload a `favicon.ico` file into the root directory in `gh-pages`, and add an extra link for it in `config.mts`.
> Try to fix several missing favicons in doc

- .github/workflows/ChangeLogCheck.yml
> Update check changelog CI

- README.md
> Add benchmark comparison in the README file

- src/correlations.jl
> Fix typo in `spectrum` docstrings

- docs/src/.vitepress/theme/VersionPicker.vue
- docs/src/.vitepress/theme/index.ts
> try to use the VersionPicker settings in `Makie.jl`

- CHANGELOG.md
- Project.toml
> bump version to `v0.23.0`

- docs/src/index.md
- docs/src/resources/acknowledgements.md
> Fix raw html for Acknowledgements

- CHANGELOG.md
- src/spectrum.jl
I slightly improve the cache initialization of the pseudo inverse method of `spectrum`. This is also a test to see if the Benchmark Tracking still returns an error as in #386 .
> Improve pseudo inverse spectrum

- CHANGELOG.md
- Project.toml
> Bump version to `v0.29.0`

- docs/src/index.md
> [Doc] Add a list of recommended packages in main page

- docs/src/users_guide/states_and_operators.md
fixing typo of equation in documentation
> [Doc] fix typo

- CHANGELOG.md
- Project.toml
> Bump to `v0.31.1`

- CHANGELOG.md
- Project.toml
> Bump version to v0.32.1

- docs/src/users_guide/time_evolution/sesolve.md
As title, some outputs of the code-block are not displayed correctly.
> [Docs] minor changes in sesolve doc

- README.md
> [no ci] Add auto-diff to README
