docs/src/api.md
src/quantum_object.jl

This helps to directly obtain the element type in `QuantumObject.data`, e.g., `Int64`, `Float64`, `ComplexF64` ...
I think this would be quite useful when developing new functionality in the future.

support `Base.eltype` for `QuantumObject`

---

src/quantum_object.jl
test/quantum_objects.jl

fix #46 
Also add tests for expected errors in generating `QuantumObjects`.

Generalize the constructor of `QuantumObject`

---

Project.toml

The excluded versions add some extra allocations. Thus, we want to avoid them

Fix compat with DiffEqCallbacks

---

src/progress_bar.jl

Optimize the display of progress bar:
- add newline (`\n`) after the process is finished (`100.0%`)
- use floor division operator (`÷`)
- use `lpad` to make the display string length be fixed for the following variables:
- `percentage_100` fix string length to `5` (e.g., `  5.0`, ` 32.0`, `100.0`)
- string length of values of minute and second be fixed to `2` (e.g., `00`, `03`, `60`)
The last one makes the string length of `print` be exactly same for very short processes. Otherwise, the update makes the output shake.

Optimize `next!` in `ProgressBar`

---

src/progress_bar.jl
test/low_rank_dynamics.jl
test/progress_bar.jl
test/runtests.jl

This PR allows users to output `ProgressBar` into general `I/O`, useful for writing logs or even into files.
- output `next!()` into general `IO` (default to `stdout`)
- export `next!()`
- Improve runtests coverage for `ProgressBar`
- change variable name `test` into `core_test` in file `test/runtest.jl`

Support general `I/O` for `ProgressBar` output

---

src/quantum_object.jl
test/quantum_objects.jl

In PR #65, we defined the type constants `OperatorBra` and `OperatorKet`. But the output of `QuantumObject` is like:
```julia
julia> Qobj(rand(4), type=OperatorKet)
Quantum Object:   type=Operator-Ket   dims=[2]   size=(4,)
4-element Vector{Float64}:
0.9398057156850064
0.14617955497643975
0.6029611022660892
0.9449902837481058
```
There's an extra `-` in the type string, we should remove it to avoid ambiguity. Maybe this would also benefit some users when they do copy-and-paste.

Modify `QuantumObject` strings in `show()`

---

src/eigsolve.jl
src/progress_bar.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
test/runtests.jl

The `ProgressBar` functionality was allocating more memory than expected. With the current version, it does not allocate memory anymore. Moreover, the `ReentrantLock` is removed, since the `print` functions are already thread-safe. I changed the `counter` as an *Atomic* object, to update it in a thread-safe manner.

Improve allocations for ProgressBar

---

docs/src/api.md
src/QuantumToolbox.jl
src/correlations.jl
src/eigsolve.jl
src/time_evolution/time_evolution.jl
test/eigenvalues_and_operators.jl
test/quantum_objects.jl

close #39 
- Update definition and docstrings of `struct EigsolveResult`
- Update definition of `iterate` for `EigsolveResult`
- New method `show` for `EigsolveResult`
- New function `eigenenergies(A::QuantumObject; sparse::Bool=false, kwargs...)`
- New function `eigenstates(A::QuantumObject; sparse::Bool=false, kwargs...)`
Also, the fields in `EigsolveResult` like `vals` and `vecs` have been renamed to `values` and `vectors`, repectively. Make the variable name  same as `LinearAlgebra.Eigen`.

New eigen solve interface

---

src/quantum_object.jl
test/quantum_objects.jl

Support the following type conversion:
```julia
using QuantumToolbox
v = Qobj(Int64[1, 1])
m = Qobj(Int64[1, 1])
Vector{ComplexF64}(v)
Matrix{ComplexF64}(m)
```
and so does `SparseVector` and `SparseMatrixCSC`

Element type conversion for `QuantumObject`

---

Project.toml
docs/src/api.md
src/QuantumToolbox.jl
src/versioninfo.jl
test/runtests.jl

close #64
Add two (same) methods which will output the information of `QuantumToolbox`, dependencies, and system information:
- `QuantumToolbox.versioninfo()`
- `QuantumToolbox.about()`: similar to `QuTiP`
The current output is something like:
```
QuantumToolbox.jl: Quantum Toolbox in Julia
≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡≡
Copyright © QuTiP team 2022 and later.
Current admin team: Alberto Mercurio, Yi-Te Huang
Package information:
====================================
QuantumToolbox  Ver. 0.7.2
LinearSolve     Ver. 2.28.0
OrdinaryDiffEq  Ver. 6.74.1
System information:
====================================
Julia Version: 1.10.2
OS       : Windows (x86_64-w64-mingw32)
CPU      : 6 × Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
Memory   : 15.918 GB
WORD_SIZE: 64
LIBM     : …
```

Introduce `versioninfo()` and `about()`

---

.github/workflows/CI.yml
src/quantum_object.jl
src/spin_lattice.jl
src/time_evolution/time_evolution.jl

close #90
The summary of this PR:
- `QuantumObject`
- `OperatorSum`
- `TimeDependentOperatorSum`
- `Lattice`
- `Julia v1.7`: Windows, MacOS, Linux-Ubuntu
- `Julia v1.8`: Linux-Ubuntu
- `Julia v1.9`: Linux-Ubuntu
- `Julia v1.10`: Windows, MacOS, Linux-Ubuntu

Immutable `QuantumObject`

---

test/runtests.jl

For local development, only run code quality tests under `VERSION >= v"1.9"`
Because `JET.test_package` does not support for `Julia v1.7`, and some errors will occur under `Julia v1.8`.

Fix local `JET` runtest

---

.github/workflows/Benchmarks.yml
.gitignore
benchmarks/.gitignore
benchmarks/Project.toml
benchmarks/runbenchmarks.jl

This PR introduces the feature of tracking the benchmark results over the commits, and produces warnings on PRs if the benchmarks regress.
It uses [https://github.com/benchmark-action/github-action-benchmark/](https://github.com/benchmark-action/github-action-benchmark/) and I used their examples as template, together with the [Lux.jl](https://github.com/LuxDL/Lux.jl) use.
Currently, I have added only the **steadystate** case, just to make it very minimal. Other benchmarks could be introduced in the following PRs, after checking that this actions works fine.

Add benchmark tracking

---

.github/workflows/Benchmarks.yml
benchmarks/correlations_and_spectrum.jl
benchmarks/dynamical_fock_dimension.jl
benchmarks/eigenvalues.jl
benchmarks/runbenchmarks.jl
benchmarks/steadystate.jl
benchmarks/timeevolution.jl
docs/make.jl
docs/src/benchmarks/benchmark_history.md

Add more benchmarks for benchmark tracking. Add also the menu link for the Bechmarks page

Add more benchmarks

---

src/arnoldi.jl
src/eigsolve.jl

This improves a bit the current `eigsolve` algorithm. Now it can detect covergence just after the first iteration. The code is also much more clean.
I have also changed the tolerances for the LinearSolve, in case of shift-inverse, since I faced instabilities in delicate cases.

Several minor changes to eigsolve

---

docs/src/api.md
src/general_functions.jl
src/negativity.jl
src/quantum_object.jl
test/quantum_objects.jl

The original `LinearAlgebra.norm` calculates standard vector norm no matter the input array is vector or matrix. But usually we calculate [Schatten p-norm](https://en.wikipedia.org/wiki/Schatten_norm) for matrices (density operators), which need to first calculate the singular values before taking the standard vector norm.
Summary for this PR:
- Support `LinearAlgebra.svdvals` (singular values) for `Qobj`
- Generalize `LinearAlgebra.norm(A::QuantumObject, p::Real=2)`:
- if `Qobj` is `Ket`, `Bra`, `OperatorKet`, or `OperatorBra`, calculate the standard vector p-norm
- if `Qobj` is `Operator` or `SuperOperator`, calculate the [Schatten p-norm](https://en.wikipedia.org/wiki/Schatten_norm)
- Since the definition of `negativity` is related to the trace-norm (Schatten 1-norm), use the above …

Support `svdvals`, generalize `norm`, and introduce `tracedist` for `Qobj`

---

.github/workflows/Benchmarks.yml

Here I change some settings for the benchmark CI. I reduced the alert threshold to 130% and the CI fail to 170%.
I have also added the comment on alert option, that comments the commit if there is a descrease of performances.

Settings change for benchmark CI

---

src/steadystate.jl
src/time_evolution/time_evolution.jl

I clean the code related to the `liouvillian_floquet` function. Specifically, I deleted the solver definition (there is only one solver, and it is not so direct to find another way to solve it at the moment). So I decided to remove it and simplify the code.

Clean the code of liouvillian_floquet

---

benchmarks/correlations_and_spectrum.jl
benchmarks/dynamical_fock_dimension.jl
benchmarks/eigenvalues.jl
benchmarks/runbenchmarks.jl
benchmarks/steadystate.jl
benchmarks/timeevolution.jl

This is a PR to improve the code format suggested in PR #116.
Since the benchmark functions modifies the variable `SUITE`.
These functions should:
- take `SUITE` as an input
- name as `benchmark_XXX!`
- `return nothing`

Fix benchmarks

---

docs/src/benchmarks/benchmark_history.md
docs/src/tutorials/logo.md

Here I try to fix the iframe related to the benchmark page. Moreover, I used the `rasterize` command to decrease the size of the figures generated by the tutorials.

Improve benchmark iframe and tutorial plots

---

src/quantum_object.jl

I find out that we have many codes like:
```julia
function f(A::QuantumObject{<:AbstractArray{T},OpType}) where {T,OpType<:QuantumObjectType} ... end 
```
where the funtion `f` basically supports all types of `QuantumObject`.
But this can be abbreviated as
```julia
function f(A::QuantumObject{<:AbstractArray{T}}) where {T} ... end
```
This can make the code more clear.

Optimize `QuantumObjectType` handling

---

docs/src/api.md
src/general_functions.jl
src/quantum_object.jl
test/quantum_objects.jl

- improve `LinearAlgebra.sqrt` to support `SparseArrays` (by using `sparse_to_dense` before `sqrt`)
- introduce `sqrtm` (same as the one in `qutip`, only works for `Operator`)
- introduce `fidelity`

Introduce `sqrtm` and `fidelity`

---

.JuliaFormatter.toml
CODE_OF_CONDUCT.md
LICENSE
README.md

- Update to same license as `qutip` and add license badge in `README`
- Add code of conduct (same as `qutip`) and also ignore it in `JuliaFormatter` (since it is also `markdown` file)
- Add the name list of admin team (and corresponding hyperlinks to their github page)
I find out that when someone wants to contribute (to this package) and make a PR, the list of reviewers includes all the qutip admins. So I thought we can at least do the same thing as `qutip`: put the admin name list on top of the README.
@albertomercurio, @lgravina1997
What do you think? Is it okay for you guys ?

Update License, Code of Conduct, and README

---

Project.toml

The previous version change had not triggered the documentation deployment.

Change version to v0.9.1

---

README.md

I rearrange the badges in a table.
This could increase the readability of these badges (even in GitHub cellphone app).

Rearrange badges in table and add `JET.jl` badge

---

src/steadystate.jl
test/steady_state.jl

The goal of this pull request is to make a step forward in the direction of fixing issue #81
In issue #81 it has been asked to implement, along with the `SteadyStateDirectSolver` already present within the library, an iterative solver using LinearSolve.jl and an eigen solver using the already implemented `eigsolve` function.
I aimed to make the code as agnostic as possible and compatible with both dense and sparse matrices on CPU and GPU. I haven't been able to make some combinations of method-device work yet, but I think this might be a good starting point.
I introduced, along with the already implemented `SteadyStateDirectSolver`, two new structs: `SteadyStateEigenSolver` and `SteadyStateLinearSolver`. While the first two don't require any argument when created, the latter allows …

Implement steady state solver using LinearSolve.jl and eigen

---

src/steadystate.jl
test/steady_state.jl

With this pull request, we fix #82. 
With this new method, we can solve the entire linear system at once and we can also get the other Fourier components of the density matrix. 
I have also introduced a little explanation in the documentation.
In the next pull requests, we could also return the other Fourier components using the `SSFloquetEffectiveLiouvillian` solver, since this was not the aim of the original issue.

Improved Floquet solver

---

src/qobj/states.jl
test/states_and_operators.jl

close #154
Summary for this PR:
- `fock` can only return `Ket`
- `basis` can only return `Ket`
- `rand_dm` can only return `Operator`
- users can specify the keyword argument `dims` for all the functions above, and will check whether the arguments are correct by directly passing them to `QuantumObject(A; type = type, dims = dims)`

Fix incorrect inputs for functions that generate states

---

docs/src/api.md
src/qobj/operators.jl
test/states_and_operators.jl

This is a PR for constructing general Spin-`j` operators (same function names within Python `qutip`), where `j` is the spin quantum numbers that can only be non-negative integer or half-integer.
- introduce `jmat`
- introduce `spin_Jx`
- introduce `spin_Jy`
- introduce `spin_Jz`
- introduce `spin_Jm`
- introduce `spin_Jp`
- introduce `spin_J_set`
- change the definition of the following Pauli operators by using `jmat`:
- `sigmap() = jmat(0.5, :+)`
- `sigmam() = jmat(0.5, :-)`
- `sigmax() = 2 * jmat(0.5, :x)`
- `sigmay() = 2 * jmat(0.5, :y)`
- `sigmaz() = 2 * jmat(0.5, :z)`

Constructing general spin-j operators

---

src/correlations.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/operators.jl
src/qobj/quantum_object.jl
src/qobj/synonyms.jl
src/steadystate.jl
src/time_evolution/time_evolution.jl

Found some typos in the function docstrings when I read through the document API page.
Also, there are some LaTeX formula that does not render correctly.

Fix some typos in the docstrings

---

ext/QuantumToolboxCUDAExt.jl
test/cuda_ext.jl

As we discussed in Zulip, we change the default `word_size` to `64` for the function `cu` in `CUDA` extension.
I also add the brief example (in README and documentation) to the runtest for `CUDA` extension. But since we don't have access to `JuliaGPU` pipeline yet, so I skipped the CI.

Change default `word_size=64` in the extension for `CUDA.jl`

---

src/QuantumToolbox.jl
src/qobj/boolean_functions.jl
src/qobj/operators.jl
src/qobj/superoperators.jl
src/time_evolution/time_evolution.jl
test/states_and_operators.jl

Currently, the return matrix type of `spre` depends on the input, but `spost` and `sprepost` always return sparse matrix.
For superoperators, it should be more feasible to use sparse matrix for large systems. Therefore, I suggest to always return sparse matrix for `spre`.
Also, I find out that if `A` is a sparse matrix, `sparse(A)` will make a copy of it. But we are going to do Kronecker product right away in generating superoperators, I don't think we need to do this copy.
Therefore, I made intrinsic functions for `spre`, `spost`, `sprepost` with multiple dispatches. To deal with different types (dense or sparse) of  input `Opeartor`.
I believe this could improve the performance when creating the Liouvillian.

Always return sparse matrices for `spre`, `spost`, and `sprepost`

---

docs/make.jl
docs/src/api.md
src/metrics.jl
src/negativity.jl
src/qobj/operators.jl
src/qobj/states.jl
test/quantum_objects.jl
test/states_and_operators.jl

close #146 
Summarize of this PR:
- Introduce `zero_ket`
- Introduce `fock_dm`
- Introduce `coherent_dm`
- Introduce `thermal_dm`
- Introduce `maximally_mixed_dm`
- minor changes in `jmat`
- Introduce `spin_state`
- Introduce `spin_coherent`
- Introduce `bell_state`
- Introduce `singlet_state`
- Introduce `triplet_states`
- Introduce `w_state`
- Introduce `ghz_state`
- ignore size threshold for document API page: `size_threshold_ignore = ["api.md"]`

Functions for generating common quantum states

---

.github/workflows/CI.yml

Two things we want to address here:
- for intel chip: use `os: macOS-13` and `arch: x64` (`macOS-latest` will ***virtually*** support `x64` by `Rosetta`)
- for Apple M-series chip: use `os: macOS-latest` and  `arch: arm64`

Improve runtest CI config

---

README.md

Since `JET.jl` updated their badge in https://github.com/aviatesk/JET.jl/pull/635, we should also update it.

Update `JET.jl` badge

---

src/progress_bar.jl
test/progress_bar.jl
test/runtests.jl

With the previous implementation, the `progress_bar` was printing the output independently on the frequency of the update.
Here, I introduced some minimum interval (one second by default), such that, updates more frequent than one second are not printed, avoiding to print thousands of lines in some cases.

Avoid repeated print of progress_bar

---

docs/src/api.md
src/correlations.jl
src/time_evolution/lr_mesolve.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/time_evolution.jl
src/time_evolution/time_evolution_dynamical.jl
test/time_evolution_and_partial_trace.jl

close #143 
1. Adjust many docstrings for time evolution functions (add `@doc raw`, LaTeX formula, and some minor changes)
2. Introduce `show` for `TimeEvolutionSol` and `TimeEvolutionMCSol`: take the brief example in README, here is the output if we `show` (or `print`) `sol` directly:
```
julia> sol = mesolve(H, ψ0, tlist, c_ops, e_ops = e_ops)
Solution of time evolution
(return code: Success)
--------------------------
num_states = 1
num_expect = 1
ODE alg.: Tsit5(; stage_limiter! = trivial_limiter!, step_limiter! = trivial_limiter!, thread = static(false),)
abstol = 1.0e-7
reltol = 1.0e-5
```
3. Adjust the return data for `sesolve`, `mesolve`, and `mcsolve`
For the current implementation, the users will only get a final state if they doesn't specify `e_ops`, which …

Introduce `show` for `TimeEvolutionSol` and `TimeEvolutionMCSol`, also, adjust return `states` and `expect` from `sesolve`, `mesolve`, and `mcsolve`

---

src/time_evolution/lr_mesolve.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl

The relative and absolute tolerances (`reltol` and `abstol`) in QuTiP is `1e-6` and `1e-8`, respectively.
Maybe we should make it the same as QuTiP, so that people can easily compare the results between two packages under the similar condition.

Change default tolerance for ODE-based solvers

---

src/time_evolution/time_evolution_dynamical.jl

This will improve the default method for defining the Krylov subspace dimension for the DSF algorithm.

Edit default krylov_dim in DSF

---

src/qobj/arithmetic_and_attributes.jl
test/quantum_objects.jl

The previous definition of `get_coherence` was valid only for pure states, although it was defined also for operators. Now it works also for density matrices.

Fix get_coherence for density matrices

---

src/qobj/quantum_object.jl
test/quantum_objects.jl

As title, this PR improves the handling for the argument `dims` while generating `QuantumObject`.
Checks whether the specified `dims` is a `Vector` and all elements are positive integers.
Also, modify some error messages to make it easier for users to debug.

improve handling for `dims` while generating `QuantumObject`

---

src/time_evolution/lr_mesolve.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/time_evolution.jl
test/time_evolution_and_partial_trace.jl

The default keyword arguments for ODE solvers are:
- `abstol = 1e-8`
- `reltol = 1e-6`
- `save_everystep = false` : this can avoid storing all the internal states in `sol.u` if users set `saveat = []`
- `save_end = true`
This PR also add some runtests for `sesolve` and `mesolve`.

introduce intrinsic constant tuple `DEFAULT_ODE_SOLVER_OPTIONS`

---

docs/src/api.md
src/qobj/operators.jl
src/qobj/states.jl
test/runtests.jl
test/states_and_operators.jl

close #147 
Summarize of this PR:
- introduce `displace` (and call it within `coherent`)
- introduce `num`
- introduce `position`
- the function is not exported because it causes conflict with `Base.position`
- introduce `momentum`
- the function is not exported because I think usually `position` and `momentum` are pairs.
- introduce `phase`
- introduce `squeeze`
- introduce `tunneling`
- introduce `qft`

Functions for generating quantum operators

---

src/progress_bar.jl
test/progress_bar.jl

With the last improvement of the `progress_bar`, the output was very often incomplete in the final print, because it was not triggered depending on the speed of the execution.
Here I have introduced another condition that checks if the **total** time exceeds the `interval` variable. If yes, then proceed with printing.

Fix progressbar end print

---

src/qobj/arithmetic_and_attributes.jl
test/quantum_objects.jl

This PR calls `tidyup!` inside `tidyup`, namely
```julia
tidyup(A, tol) = tidyup!(copy(A), tol)
```
Also, use multiple dispatch for different element types `T<:Real` or `T<:Complex` for function `tidyup!`:
If `T<:Real`, then use the origin method: 
```julia
@. A = T(abs(A) > tol) * A
```
If `T<:Complex`, then use the following method:
```julia
@. A = T(abs(real(A)) > tol) * real(A) + 1im * T(abs(imag(A)) > tol) * imag(A)
```

Handle `tidyup` separately for real and imaginary values

---

src/qobj/arithmetic_and_attributes.jl

As title, the argument `p` is missing in `normalize!`

Fix missing `p` for in-place `normalize`

---

docs/src/api.md
src/qobj/states.jl
src/utilities.jl
test/states_and_operators.jl

This PR introduces `rand_ket`, and also modify the method for generating random density matrix `rand_dm`.
I think the current method for generating random density matrix is not random enough. Because the real value of off-diagonal elements are always positive. 
Here, I implement the method to generate random density matrix from ***Ginibre ensemble***, which is also the default method in `qutip`. I think this method is the more standard one in the literature.
Furthermore, with this method, we can specify the `rank` of the density matrix, i.e., the number of eigenvalues which are positive. The other eigenvalues will be very close to zero (`< 1e-15`).

Introduce `rand_ket` and generate `rand_dm` using Ginibre ensemble method

---

src/qobj/quantum_object.jl
test/aqua.jl
test/code_quality.jl
test/cuda_ext.jl
test/jet.jl
test/negativity_and_partial_transpose.jl
test/quantum_objects.jl
test/runtests.jl
test/states_and_operators.jl
test/time_evolution_and_partial_trace.jl

I realize that we can add keyword argument `verbose = true` in `@testset`:
```julia
@testset "Test" verbose = true begin
@testset "Sub-Test 1" begin
...
end
@testset "Sub-Test 2" begin
...
end
end
```
So I tried to divide some tests into several sub-testsets, which I think it could improve the readability while we are debugging.
This PR also made some small changes for the following functions: `:(==)`, `isequal`, `isapprox`.
I think it would be better to check the `type` and `dims` first, and then check the `data` at the end.
Furthermore, this PR allows users to pass `kwargs` directly to `Base.isapprox`.

Divide some tests into sub-testsets

---

.github/workflows/Benchmarks.yml
.github/workflows/CI.yml
.github/workflows/FormatCheck.yml
.github/workflows/documentation.yml

This PR changes the `paths-ignore` filter in CI pipeline configs to `paths` filter.
In this way, we don't need to add `[skip ci]` while modifying `README.md`, `.gitignore`, and so on.

Optimize CI pipline using `paths` filter

---

Project.toml
src/time_evolution/sesolve.jl
test/time_evolution_and_partial_trace.jl

This is the first of a long series of Pull Requests for fixing all the type instabilities of the functions.
Here, I have downgraded the maximum version of DiffEqCallbacks.jl to v3.1.0, since after that version it generates type instabilities. Moreover, I made some small changes to the code.

Fix type instabilities for `sesolve`

---

benchmarks/timeevolution.jl
src/time_evolution/sesolve.jl
src/utilities.jl
test/time_evolution_and_partial_trace.jl

With the previous PR, I fixed the type instabilities of the `sesolve` function.
However, a weak type instability was still present at the level of the `ODEProblem` generation. By weak I mean that the type of the `ODEProblem` was known up to a `Union`.
Fixing this will help me on fixing type instabilities for the `mesolve` and `mcsolve` functions.
I think that I have introduced a very smat way to deal with multiple dispatch with keyword arguments. For example, the `progress_bar` argument now supports both a `Bool` type and a `Val` type, with the second one as a default to avoid weak type instabilities. In this way, the user can still use `progress_bar = true,false`, with the price to pay of having weak type instabilities.

Improve type-stability of `sesolve`

---

src/qobj/quantum_object.jl
test/quantum_objects.jl

This PR allows users to extract the real or imaginary parts of an `Qobj`.

support `real` and `imag` for `Qobj`

---

src/qobj/states.jl

As title, because usually people will make a zero ket first and start to stack some values at different position of the vector. 
It would be better to generate it with the element-type `ComplexF64`, so that users can directly assign complex values to it.

make element-type of `zero_ket` as complex

---

docs/src/api.md
src/qobj/boolean_functions.jl
src/qobj/operators.jl
test/quantum_objects.jl
test/states_and_operators.jl

This PR introduces two functions which are the same ones in `qutip`:
- `rand_unitary`: Returns a random unitary with two different provided methods.
- `isunitary`: Test whether a `Qobj` $$U$$ is unitary operator. This function calls `Base.isapprox` to test whether $$U U^\dagger$$ is approximately equal to identity operator.

introduce `rand_unitary` and `isunitary`

---

src/qobj/arithmetic_and_attributes.jl
test/quantum_objects.jl

fix type instabilities for `exp`

---

docs/src/api.md
src/QuantumToolbox.jl
src/qobj/operator_sum.jl
src/time_evolution/time_evolution.jl

Here I improved the `OperatorSum` struct, which no longer requires the list of operators to be a list of Qobjs. This is useful if we deal with a more general sum of matrices.

Improve OperatorSum

---

src/correlations.jl
src/qobj/eigsolve.jl
src/steadystate.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/time_evolution.jl

Here I improve the way we handle `c_ops`. In this way, the `liouvillian` function or anything related to `c_ops` should be much easier to read.

Improve c_ops handling

---

.buildkite/CUDA_Ext.yml
.buildkite/pipeline.yml
docs/src/index.md
docs/src/users_guide/extensions/cuda.md
test/cuda_ext.jl

As title.
Now, the buildkite pipeline will be triggered dynamically depending on the settings in `.buildkite/pipeline.yml` with the buildkite plugin called `forerunner-buildkite-plugin`.
After this PR, it will trigger `.buildkite/CUDA_Ext.yml` only if the following files/paths has been changed:
- `.buildkite/pipeline.yml`
- `.buildkite/CUDA_Ext.yml`
- `src/**`
- `ext/QuantumToolboxCUDAExt.jl`
- `test/runtests.jl`
- `test/cuda_ext.jl`
- `Project.toml`
In order to re-trigger all CI-pipelines again, I add the following code into the runtests and also documentation:
```julia
CUDA.allowscalar(false) # Avoid unexpected scalar indexing
```

Avoid scalar indexing in runtests and fix buildkite pipeline

---

docs/src/users_guide/states_and_operators.md
docs/src/users_guide/tensor.md
src/metrics.jl
src/negativity.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/operators.jl
src/qobj/states.jl
src/qobj/superoperators.jl
src/qobj/synonyms.jl
src/steadystate.jl
src/time_evolution/mesolve.jl
test/states_and_operators.jl

- add `\hat{}` to all operators in docs
- modify `fcreate` and `fdestroy` to make them compatible with `qutip`

Add `\hat` to docs and make `fcreate`, `fdestroy` compat with `qutip`

---

src/qobj/operators.jl

Fix return type of `rand_unitary`

---

.github/workflows/CI.yml

We should run the tests on `macOS` with `arch: arm64` instead of `x64`

fix CI config

---

.github/workflows/CI-Julia-nightly.yml

Add pipeline to run core and code quality tests under `Julia nightly`

---

.github/pull_request_template.md
.github/workflows/FormatCheck.yml
Makefile
docs/README.md

This PR introduces `Makefile` to support `make` commands.
In this way, we can simplify several commands during development:
For example:
```
make docs   # build documentation
make test   # run tests
make format # format files with JuliaFormatter
```

Introduce `Makefile` to make development more convenient

---

src/qobj/operator_sum.jl
src/time_evolution/mesolve.jl
src/time_evolution/time_evolution.jl
test/core-test/steady_state.jl

In the case of `mesolve`, the current implementation requires that `TimeEvolutionOperatorSum` contains only `SuperOperator`s. With this PR I relax this request, converting it to `SuperOperator` internally.

Automatically convert TimeDependentOperatorSum to `liouvillian`

---

docs/make.jl
docs/src/api.md
docs/src/users_guide/steadystate.md
src/steadystate.jl
test/core-test/steady_state.jl

- add missing docstrings for `steadystate` and corresponding solvers.
- update documentation for `steadystate`.

[Docs] Update docstring and documentation for `steadystate`

---

src/time_evolution/lr_mesolve.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
src/time_evolution/time_evolution_dynamical.jl
test/core-test/time_evolution.jl

The current `times` of different time evolution solutions are basically obtained from `sol.t`.
However, the length of `sol.t` actually depends on the keyword argument `saveat`.
To make it consistent with the docstrings, and also align with `QuTiP`, I put `t_l` into `p = (..., times = t_l, ...)`, and then pass it to different time evolution solutions with `sol.prob.p.times`.
After this PR, the type of `sol.times` are all the same as `Vector{<:Real}` for different time evolution solutions, and the length should be equal to the input `tlist`.

Fix incorrect `times` in time evolution solutions

---

docs/src/users_guide/time_evolution/intro.md
docs/src/users_guide/time_evolution/solution.md

- add problems (sesolveProblem, mesolveProblem, etc) to the table in Time evolution introduction page.
- update content of time evolution solution

[Docs] update time evolution introduction and solution

---

docs/src/users_guide/steadystate.md
docs/src/users_guide/time_evolution/solution.md

In PR #245, I used 
```julia
bla bla bla...; nothing # hide
``` 
at several endings of the `@example` block to avoid unnecessary output.
However, the keyword `# hide` will hide the entire line of the code in documentation, which causes some codes missing.
Therefore, I changed from
```julia
...
...; nothing # hide
```
into 
```julia
...
...
nothing # hide
```
I also fixed some typos in the documentation.

[Docs] Fix typo in `@example` block

---

docs/src/tutorials/logo.md
docs/src/tutorials/lowrank.md
docs/src/users_guide/steadystate.md
docs/src/users_guide/time_evolution/solution.md

Here I reduce the size of the Figures in the Documentation, in order to have a better reading experience.

[DOCS] Reduce figures size in Documentation

---

src/correlations.jl
src/qobj/eigsolve.jl
src/qobj/operator_sum.jl
src/steadystate.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
test/core-test/steady_state.jl
test/core-test/time_evolution.jl

Here I added the support for `Tuple` types in the context of time evolution, like `sesolve` and similars. Also for `OperatorSum` and `TimeDependentOperatorSum`.
In this way, we could support in a type stable way also lists of quantum objects with different type.

Extend the support to `Tuple` in time_evolution

---

benchmarks/eigenvalues.jl
docs/src/api.md
docs/src/users_guide/steadystate.md
src/time_evolution/time_evolution.jl
src/utilities.jl
test/core-test/eigenvalues_and_operators.jl
test/core-test/generalized_master_equation.jl

This PR changed `n_th` to `n_thermal` to align with qutip (also the return value).
This PR also fix the incorrect fontsize of figure in documentation.

Replace `n_th` with `n_thermal` for QuTiP compatibility

---

docs/Project.toml
docs/src/type_stability.md

Here I write the page about type-instabilities. It is a specific page for people interested in performances on their numerical calculations.

[DOCS] add Documentation about type instabilities

---

Project.toml
README.md
docs/make.jl
docs/src/type_stability.md
src/versioninfo.jl

Here I remove Luca from the list of the maintainers. I have also added a minor sentence in the type instability section.

Remove Luca from list of maintainers

---

src/utilities.jl

Fix return type precision for `n_thermal`

---

docs/src/api.md
src/utilities.jl
test/core-test/utilities.jl

- Introduce `const PhysicalConstants::NamedTuple`, which stores some constant values listed in [*CODATA recommended values of the fundamental physical constants: 2022*](https://physics.nist.gov/cuu/pdf/wall_2022.pdf)
- Add new energy units for `convert_unit`

Introduce `PhysicalConstants` and new energy units

---

docs/src/users_guide/time_evolution/solution.md
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/ssesolve.jl

The original default value of `saveat` is given by
```julia
saveat = e_ops isa Nothing ? t_l : [t_l[end]]
```
This causes ambiguity when user specify `e_ops = []`, because:
```julia
[] isa Nothing # false
```
Therefore, I change it to
```julia
saveat = is_empty_e_ops ? t_l : [t_l[end]]
```
where `is_empty_e_ops` is pre-defined as
```julia
is_empty_e_ops = isempty(e_ops)
```
and this works becasue
```julia
isempty([]) # …
```

Fix default value of keyword parameter `saveat`

---

.buildkite/CUDA_Ext.yml
.github/workflows/CI.yml
.github/workflows/Code-Quality.yml
README.md

Since the Julia v1.11 has released, we should update the CI config and buildkite config

Add `Julia v1.11` to CI and buildkite config

---

docs/src/users_guide/states_and_operators.md
docs/src/users_guide/steadystate.md
docs/src/users_guide/time_evolution/intro.md
docs/src/users_guide/time_evolution/mcsolve.md
docs/src/users_guide/time_evolution/mesolve.md
docs/src/users_guide/time_evolution/sesolve.md
docs/src/users_guide/time_evolution/solution.md
docs/src/users_guide/time_evolution/stochastic.md
docs/src/users_guide/time_evolution/time_dependent.md

[Doc] update documentation for `sesolve` and `mesolve`

---

src/QuantumToolbox.jl
src/time_evolution/mcsolve.jl
src/time_evolution/ssesolve.jl
test/core-test/time_evolution.jl
test/runtests.jl

Reproducibility is a fundamental feature for Monte Carlo simulations and Stochastic Solvers. The previous implementation on `mcsolve` involved the explicit definition of the `seeds` vector as an argument. Now, instead, we just need to put the random number generator (together with some optional seed). Given this RNG, every trajectory is completely reproducible.
Moreover, I have also added this feature on `ssesolve`.

Improve random number generation on mcsolve and ssesolve

---

src/QuantumToolbox.jl
src/deprecated.jl

This PR adds a file called `src/deprecated.jl`, which gathers all the deprecated functions which will be removed in the next major release.
In this case, we don't need to push a major release frequently because of deprecating some functionalities.
I saw this idea long time ago in some repo., I think it would be nice to have this for future development.

Add deprecated file

---

src/time_evolution/mesolve.jl

Improve error message for time-dependent Hamiltonian in `mesolve`

---

src/QuantumToolbox.jl
src/qobj/quantum_object.jl
src/qobj/quantum_object_evo.jl
test/core-test/quantum_objects_evo.jl

This PR provides the `show` method for `QobjEvo`

Add `show` method for `QobjEvo`

---

.github/ISSUE_TEMPLATE/bug_report.yaml
src/versioninfo.jl

Add `SciMLOperators` to `versioninfo`

---

src/QuantumToolbox.jl
src/qobj/superoperators.jl
src/time_evolution/mesolve.jl
src/time_evolution/time_evolution.jl
test/core-test/quantum_objects.jl
test/core-test/quantum_objects_evo.jl
test/core-test/time_evolution.jl

This PR support constructing time-dependent Liouvillian from a given `Operator` type `QobjEvo`.
@albertomercurio 
Do you think we can remove those `f::Function = identity (liouvillian)` keyword arguments now ?

Support time-dependent `liouvillian`

---

docs/Project.toml
docs/make.jl
docs/src/api.md
docs/src/bibliography.bib
docs/src/bibliography.md
docs/src/tutorials/lowrank.md
src/spin_lattice.jl
src/time_evolution/lr_mesolve.jl
test/core-test/low_rank_dynamics.jl

With this PR I clean the low rank master equation code, including the related documentation and the docstrings. Now everything should be much clearer.
I have also added the possibility to build a bibliography with bibtex, such that all the references of the documentation are seamlessly stored in one single page.
In the future I will further improve those functions, but for the moment this may be ok for a good documentation.

Clean low-rank mesolve and add Documentation bibliography

---

src/wigner.jl
test/core-test/wigner.jl

Here I make the `WignerClenshaw` as default method for the `wigner` function, just like in qutip. Moreover, I changed the keyword argument name from `solver` to `method`, just as qutip. Finally, I improved the docstring.

Make clenshaw method as default for wigner

---

docs/src/api.md
src/QuantumToolbox.jl
src/qobj/boolean_functions.jl
src/qobj/quantum_object.jl
src/qobj/quantum_object_base.jl
src/qobj/quantum_object_evo.jl
src/qobj/superoperators.jl
src/qobj/synonyms.jl
src/utilities.jl
test/core-test/quantum_objects.jl
test/core-test/quantum_objects_evo.jl
test/core-test/time_evolution.jl

Support time-dependent `lindblad_dissipator`

---

src/qobj/quantum_object_evo.jl
src/qobj/synonyms.jl
src/time_evolution/mcsolve.jl
test/core-test/quantum_objects_evo.jl
test/core-test/time_evolution.jl
test/runtests.jl

- Add a lazy method to construct `QobjEvo`
- ~make `mcsolveProblem` accept `H_eff::AbstractQuantumObject` to fix extra `ScalarOperator` for time-independent `mcsolve`.~ This breaks many things in dynamical solvers
- improve runtests to make sure time-independent problems are `MatrixOperator`
Please mention the related issues or PRs here. If the PR fixes an issue, use the keyword …

A lazy method to construct `QobjEvo`

---

src/time_evolution/sesolve.jl
src/time_evolution/time_evolution_dynamical.jl
test/core-test/time_evolution.jl

With this PR I improve the handling of SciMLOperator in `sesolveProblem`. More specifically, the `mcsolveProblem` was returning a `ScaledOperator` instead of a simpler `MatrixOperator`. Now, it returns a `MatrixOperator`, which should make the operations a bit faster.

Improve SciMLOperator handling of sesolveProblem

---

src/time_evolution/mcsolve.jl
test/runtests.jl

As title, this PR will give the possibility to choose wether to normalize the states in `mcsolve` or not. With true, as default, like in QuTiP.

Add normalize_states option in mcsolve

---

.github/workflows/SpellCheck.yml
.typos.toml
README.md
docs/src/index.md
docs/src/tutorials/lowrank.md
docs/src/users_guide/states_and_operators.md
src/linear_maps.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/boolean_functions.jl
src/qobj/superoperators.jl
src/steadystate.jl
src/time_evolution/mcsolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution_dynamical.jl

As title.
"[typos](https://github.com/crate-ci/typos)" will check our spelling, tell us where each typo is located, and give us suggestions.
I also add the ignore file for the word: `ket`, since we use it a lot.
@albertomercurio 
If you agree with this, I will fix all the typos detected by this CI.

Add spell check CI and fix typos

---

.github/workflows/documentation.yml
.gitignore
docs/README.md
docs/package.json

Add instructions about building docs locally

---

docs/make.jl
docs/src/getting_started.md
docs/src/index.md

Change Homepage appearance

---

Makefile
README.md
docs/README.md
docs/src/index.md

Add Makefile command for starting Vitepress locally and some minor changes

---

docs/make.jl
docs/src/.vitepress/config.mts
docs/src/index.md
docs/src/resources/api.md
docs/src/resources/bibliography.bib
docs/src/users_guide/states_and_operators.md
docs/src/users_guide/time_evolution/intro.md
docs/src/users_guide/time_evolution/mesolve.md
docs/src/users_guide/time_evolution/sesolve.md
docs/src/users_guide/time_evolution/solution.md

updates for documentation

---

docs/make.jl
docs/src/.vitepress/theme/VersionPicker.vue

Fix documentation

---

test/core-test/time_evolution.jl

With this PR I add the test for the number of allocations in all the time-evolution functions, in order to keep track of the memory allocations in the future.
Moreover, I clean a bit the file. I defined a global problem, and from that I tested all the cases like `sesolve`, `mesolve`, ....

add allocations tests and clean time evolution tests

---

CHANGELOG.md
Project.toml

As title, this PR is also a demonstration of bumping version number together with updating `CHANGELOG.md` before a new release.

Bump version to `v0.21.5`

---

README.md
docs/make.jl
docs/src/index.md
docs/src/tutorials/cluster.md

As title, I made a tutorial on how to run on a cluster with many nodes. I think that this tutorial is very important to show how this package is powerful, allowing to run intensive parallel simulations seamlessly on a cluster.

Make a tutorial on HPC simulations

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/tutorials/cluster.md
docs/src/tutorials/lowrank.md
src/spin_lattice.jl
test/core-test/low_rank_dynamics.jl

Here I change the `SingleSiteOperator` with a more general one `MultiSiteOperator`, allowing to generate an arbitrary product operator of a multipartite system.
This PR fixes #322.

Change SingleSiteOperator with MultiSiteOperator

---

CHANGELOG.md
benchmarks/correlations_and_spectrum.jl
docs/make.jl
docs/src/resources/api.md
docs/src/resources/bibliography.bib
docs/src/users_guide/two_time_corr_func.md
src/QuantumToolbox.jl
src/correlations.jl
src/deprecated.jl
src/spectrum.jl
test/core-test/correlations_and_spectrum.jl

The current implementation of `spectrum` does not align with QuTiP (see the documentation [here](https://qutip.readthedocs.io/en/qutip-5.0.x/guide/guide-correlation.html)). The `spectrum` should only return the value of spectrum corresponding to the user specified `ω_list`. Also, the peudo-inverse method is missing.
Furthermore, in QuTiP, the spectra obtained from `fft` of the correlation function is done by a function …

Make `spectrum` and `correlation` align with QuTiP

---

docs/make.jl
docs/src/resources/bibliography.bib
docs/src/users_guide/HEOM.md

Add a brief introduction of HEOM approach in documentation and some links to `HierarchicalEOM.jl`

[Doc] HEOM documentation page

---

CHANGELOG.md
Project.toml

As title.
I have also bump the version number to `v0.23.1`, so that we can directly release a new version after this PR is merged.
fix #332

Fix `[compat]` of `DiffEqCallbacks.jl`

---

CHANGELOG.md
docs/make.jl

The documentation Changelog page's each release tag is broken. This PR will fix it.

Fix release date format in `CHANGELOG`

---

CHANGELOG.md
src/qobj/quantum_object_evo.jl
src/time_evolution/sesolve.jl
test/core-test/quantum_objects_evo.jl

- add new methods to generate `QobjEvo` with input type `Tuple{QuantumObject,Function}`.
- add argument checks for each coefficient `Function` by using `Base.methods`.
close #338

Improve the construction of `QobjEvo`

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/users_guide/QuantumObject/QuantumObject_functions.md
src/qobj/arithmetic_and_attributes.jl
test/core-test/quantum_objects.jl
test/core-test/quantum_objects_evo.jl
test/runtests.jl

Support `zero` and `one` for `AbstractQuantumObject`

---

CHANGELOG.md
Project.toml
docs/make.jl
docs/src/resources/api.md
docs/src/tutorials/logo.md
ext/QuantumToolboxCairoMakieExt.jl
src/QuantumToolbox.jl
src/visualization.jl
test/ext-test/cairomakie/cairomakie_ext.jl
test/runtests.jl

This PR introduces plotting capabilities in QuantumToolbox (starting from the `plot_wigner` function implemented in QuTip). 
To reduce the impact on loading time, I wrote an extension for the CairoMakie library, such that the necessary code is not loaded by default. Moreover, this allows extending the scheme to additional plotting libraries like PyPlot or Plots (although I haven't done it).
The `plot_wigner` function implements 2D and 3D projections of the Wigner and reproduces QuTip's output as faithfully as possible.
fix #86

Add Wigner plotting via CairoMakie

---

.github/workflows/Code-Quality.yml
docs/make.jl
docs/src/resources/api.md
src/qobj/arithmetic_and_attributes.jl
src/qobj/boolean_functions.jl
src/qobj/functions.jl
src/qobj/operators.jl
src/qobj/quantum_object.jl
src/qobj/quantum_object_base.jl
src/qobj/quantum_object_evo.jl
src/qobj/synonyms.jl

Simplify synonyms

---

src/qobj/dimensions.jl
src/qobj/quantum_object_base.jl
src/qobj/space.jl
test/core-test/correlations_and_spectrum.jl
test/core-test/steady_state.jl

Fix type-instability for `prod`

---

README.md
docs/make.jl
docs/src/index.md
docs/src/resources/acknowledgements.md

Zulip has recently approved our request for a free upgrade to the Zulip Cloud Standard subscription. As requested, we are encouraged to acknowledge their sponsorship on our main page.

Add Zulip sponsor

---

docs/src/resources/api.md
docs/src/tutorials/lowrank.md
ext/QuantumToolboxCUDAExt.jl
src/correlations.jl
src/negativity.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/block_diagonal_form.jl
src/qobj/dimensions.jl
src/qobj/eigsolve.jl
src/qobj/functions.jl
src/qobj/quantum_object.jl
src/qobj/quantum_object_base.jl
src/qobj/quantum_object_evo.jl
src/qobj/space.jl
src/qobj/superoperators.jl
src/spectrum.jl
src/spin_lattice.jl
src/steadystate.jl
src/time_evolution/lr_mesolve.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
src/time_evolution/time_evolution_dynamical.jl
test/core-test/quantum_objects.jl
test/core-test/quantum_objects_evo.jl
test/runtests.jl

As title
This is an add-on PR for PR #360. The admins will have a discussion to decide whether to implement this or not.

introduce field `dimensions`, and property `dims`

---

src/metrics.jl
src/negativity.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/eigsolve.jl
src/qobj/functions.jl
src/qobj/operators.jl
src/qobj/quantum_object.jl
src/qobj/quantum_object_evo.jl
src/qobj/states.jl
src/wigner.jl
test/core-test/quantum_objects.jl
test/core-test/quantum_objects_evo.jl

The current `show` for `Qobj` tuples print as the following style:
```julia-repl
julia> a = destroy(2);
julia> (a, a', a + a')
(Quantum Object:   type=Operator   dims=[2]   size=(2, 2)   ishermitian=false
2×2 SparseMatrixCSC{ComplexF64, Int64} with 1 stored entry:
⋅      1.0+0.0im
⋅          ⋅    , Quantum Object:   type=Operator   dims=[2]   size=(2, 2)   ishermitian=false
2×2 Adjoint{ComplexF64, …
```

Improve `show` for `Qobj`/`QobjEvo` lists

---

CHANGELOG.md
src/qobj/functions.jl
src/qobj/superoperators.jl
src/utilities.jl
test/core-test/quantum_objects_evo.jl

As title.
Our package already supports the Kronecker product between `AbstractArray` and `AbstractSciMLOperator`. But it uses the lazy tensor method given in `SciMLOperator.jl`. We should throw an warning so that users understand that the lazy tensor method is used.

Improve lazy tensor warning for `SciMLOperators`

---

CHANGELOG.md
Project.toml

[no ci] bump version to `v0.25.0`

---

CHANGELOG.md
src/time_evolution/time_evolution_dynamical.jl
test/core-test/dynamical_fock_dimension_mesolve.jl

The previous implementation was returning an error when using the `saveat` argument. This was caused by a wrong saving of the `dims` during the evolution.

Fix dynamical fock dimension saving

---

CHANGELOG.md
src/qobj/functions.jl
test/core-test/quantum_objects.jl

Support a list of observables for `expect`

---

CHANGELOG.md
src/time_evolution/lr_mesolve.jl
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
test/core-test/time_evolution.jl

I add some checks on the `tlist` argument. It throws an error if `tlist` is either empty, not sorted or containing repeated values.
Fixes #377

Check `tlist` properties

---

.github/pull_request_template.md
README.md
docs/src/resources/contributing.md

I think the title of contribution page should change to `Contributing to Quantum Toolbox in Julia` instead of `QuantumToolbox.jl`. Since we also have `HEOM.jl` and tutorial repo. and maybe other sub-packages in the future.
Furthermore, this PR also improve the guidance of `make test` command with specifying `GROUP` argument.

[Docs] Minor changes to contribute page

---

CHANGELOG.md
ext/QuantumToolboxCUDAExt.jl
src/qobj/functions.jl
test/ext-test/gpu/cuda_ext.jl
test/runtests.jl

Fix CUDA sparse_to_dense

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/users_guide/QuantumObject/QuantumObject.md
ext/QuantumToolboxCUDAExt.jl
src/deprecated.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/eigsolve.jl
src/qobj/functions.jl
src/qobj/operators.jl
src/qobj/quantum_object.jl
src/qobj/quantum_object_evo.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/smesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
src/wigner.jl
test/core-test/eigenvalues_and_operators.jl
test/core-test/generalized_master_equation.jl
test/core-test/negativity_and_partial_transpose.jl
test/core-test/quantum_objects.jl
test/core-test/states_and_operators.jl
test/core-test/wigner.jl
test/ext-test/gpu/cuda_ext.jl

Rename function `sparse_to_dense` as `to_dense` and `dense_to_sparse` as `to_sparse`

---

docs/src/getting_started/logo.md
src/correlations.jl

Minor changes in documentation and docstrings

---

CHANGELOG.md
src/time_evolution/smesolve.jl
test/core-test/time_evolution.jl

This PR fixes a erroneous definition of the stochastic term in `smesolve`, improving its stability.

Fix of erroneous definition of stochastic term in  `smesolve`

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/users_guide/cluster.md
src/deprecated.jl
src/spin_lattice.jl
test/core-test/low_rank_dynamics.jl

I change the name of the `MultiSiteOperator` function to `multisite_operator`, since functions are always lower case here. Only structs can have upper case names.

Change MultiSiteOperator function name to multisite_operator

---

CHANGELOG.md
src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/smesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
test/core-test/time_evolution.jl

Fix time evolution output when using `saveat`

---

CHANGELOG.md
src/time_evolution/smesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl

This PR improves the generation of the ensemble problem for `ssesolve`. Moreover, the stochastic processes were still using the old structure of parameters using `NamedTuple`. I changed it to be totally generic, with the `NullParameters` default value.

Improve ensemble generation of ssesolve and change parameters on stochastic processes

---

CHANGELOG.md
src/QuantumToolbox.jl
src/time_evolution/smesolve.jl
src/time_evolution/ssesolve.jl
src/time_evolution/time_evolution.jl
test/core-test/time_evolution.jl

The current implementation of `ssesolve` and `smesolve` only supports `sc_ops` to be either a `Vector` or a `Tuple`.
This constraints the solver to use the non-diagonal noise, as the diagonal one can only be implemented in the case of a single collapse operator. This cannot be inferred automatically, as the solver may depend on the length of `sc_ops`, creating type instability.
Here I implement the support for a single …

Support for single `sc_ops` for faster specific method in `ssesolve` and `smesolve`

---

CHANGELOG.md
benchmarks/eigenvalues.jl
src/qobj/eigsolve.jl
src/steadystate.jl
test/core-test/eigenvalues_and_operators.jl

Align `eigenstates` and `eigenenergies` to QuTiP

---

CHANGELOG.md
src/QuantumToolbox.jl
src/time_evolution/callback_helpers/callback_helpers.jl
src/time_evolution/callback_helpers/mcsolve_callback_helpers.jl
src/time_evolution/callback_helpers/mesolve_callback_helpers.jl
src/time_evolution/callback_helpers/sesolve_callback_helpers.jl
src/time_evolution/callback_helpers/smesolve_callback_helpers.jl
src/time_evolution/callback_helpers/ssesolve_callback_helpers.jl
test/core-test/time_evolution.jl

The current implementation of the save callbacks relies on `PresetTimeCallback`, which adds `tstops` to the integrator and can lead to extra, unnecessary evaluations of the differential equation. By contrast, using `FunctionCallingCallback` avoids adding `tstops`; it simply interpolates the solution at the desired time points. 
This approach also resolves the issue where the solution’s stability depends on whether the …

Change save callbacks from `PresetTimeCallback` to `FunctionCallingCallback`

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/users_guide/states_and_operators.md
src/qobj/functions.jl
src/qobj/synonyms.jl
test/core-test/quantum_objects.jl

The functions `mat2vec` and `vec2mat` are called `operator_to_vector` and `vector_to_operator`, respectively.
Therefore, I made them as synonyms.

Introduce `operator_to_vector` and `vector_to_operator`

---

CHANGELOG.md
docs/src/resources/api.md
src/entropy.jl
test/core-test/entropy_and_metric.jl

This PR fix the ambiguity of the function `entanglement`.
Also, introduces `concurrence`.
fix #418
implement `concurrence` listed in issue #414

Fix `entanglement` and introduce `concurrence`

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/resources/bibliography.bib
docs/src/users_guide/states_and_operators.md
src/metrics.jl
test/core-test/entropy_and_metric.jl

This PR implements the following metric functions:
- `hilbert_dist`
- `hellinger_dist`
- `bures_dist`
- `bures_angle`
close #414

Introduce some metric functions

---

CHANGELOG.md
docs/src/users_guide/steadystate.md
ext/QuantumToolboxCUDAExt.jl
src/steadystate.jl
src/utilities.jl
test/core-test/steady_state.jl
test/ext-test/gpu/cuda_ext.jl

The `SteadyStateODESolver` method for `steadystate` was different in terms of arguments given. Here I align it to the other solvers, making it easier to use. I also made it more efficient avoiding allocations when computing the terminate function.
Moreover, I slightly improve the support for GPU, supporting now also CSR sparse matrices.

Align `steadystate` ODE solver and improve GPU support

---

CHANGELOG.md
src/time_evolution/mesolve.jl
src/time_evolution/smesolve.jl
test/core-test/time_evolution.jl

Add the support for `OperatorKet` state input for `mesolve` and `smesolve`.

Add support for `OperatorKet` state input for `mesolve` and `smesolve`

---

.buildkite/CUDA_Ext.yml
.buildkite/pipeline.yml

Update buildkite CI pipeline settings

---

ext/QuantumToolboxCUDAExt.jl
src/utilities.jl

Move `_change_eltype`  in CUDA extension to `utilities.jl` and rename it as `_convert_eltype_wordsize`

move and rename eltype conversion

---

CHANGELOG.md
ext/QuantumToolboxCUDAExt.jl
test/ext-test/gpu/cuda_ext.jl

The PR [here](https://github.com/JuliaGPU/CUDA.jl/pull/2729) is not going to be merged. In the meantime I made a few changes to make the CUDA conversion more general using `Adapt`.
Fixes #436

Make CUDA conversion more general

---

CHANGELOG.md
src/qobj/states.jl

Here I do a small change in the generation of a `fock` state, using comprehension instead of creating a zero vector and then mutating one element. This would support Zygote.jl differentiation, as it doesn't support mutating arrays.

Make `fock` non-mutating

---

src/entropy.jl
src/qobj/eigsolve.jl
src/qobj/operators.jl
src/qobj/states.jl
src/spin_lattice.jl
src/steadystate.jl
src/time_evolution/lr_mesolve.jl
src/time_evolution/time_evolution.jl
src/time_evolution/time_evolution_dynamical.jl
src/wigner.jl
test/core-test/generalized_master_equation.jl
test/core-test/low_rank_dynamics.jl
test/core-test/steady_state.jl

Format the code according to the new version of JuliaFormatter.jl

---

CHANGELOG.md
src/entropy.jl
src/qobj/dimensions.jl
src/qobj/quantum_object_base.jl
test/core-test/quantum_objects.jl

Support different length for `to` and `from` on GeneralDImensions

---

.github/workflows/CI.yml
CHANGELOG.md
Project.toml
docs/make.jl
docs/src/getting_started/logo.md
docs/src/users_guide/extensions/cairomakie.md
ext/QuantumToolboxMakieExt.jl
src/visualization.jl
test/ext-test/cpu/cairomakie/Project.toml
test/ext-test/cpu/makie/Project.toml
test/ext-test/cpu/makie/makie_ext.jl
test/runtests.jl

The previous extension was only limited to CairoMakie.jl, which is only one of many backends available in the Makie.jl ecosystem.
Here, I make the extension more general, by defining it only for the Makie.jl, which is common to alls the backends.
In this way, the user can also use GLMakie.jl or WGLMakie.jl, for example. Allowing for interactive data plot.

Make Makie extension more general

---

CITATION.bib
README.md
docs/make.jl
docs/src/getting_started/cite.md
docs/src/index.md

This PR adds the citation bibtex and related elements including:
- add `CITATION.bib` file
- replace Zenodo DOI badge in `README` as: [![Cite](https://img.shields.io/badge/cite-arXiv%3A2504.21440_(2023)-blue)](https://doi.org/10.48550/arXiv.2504.21440)
- add a `Cite` section in `README`
- add `Cite us` button in documentation main page
- add `Cite` page in documentation
Regarding the `QuantumToolbox.cite()` function (like …

Add citation bibtex for arXiv preprint

---

src/qobj/quantum_object_evo.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl

The blocking pull request have been merged. So we can simplify a bit the code.

Simplify QobEvo creation and time evolution

---

CHANGELOG.md
benchmarks/correlations_and_spectrum.jl
docs/src/resources/api.md
src/QuantumToolbox.jl
src/spectrum.jl
test/core-test/correlations_and_spectrum.jl
test/ext-test/gpu/cuda_ext.jl

Lanczos-based `spectrum` method.
Resolves #463.
This PR implements the non-symmetric variant of the Hermitian Lanczos method described in [Koch2011](https://www.cond-mat.de/events/correl11/manuscripts/koch.pdf).
The pseudo-code for the non-symmetric Lanczos algorithm can be found in Algorithm 6.6 of [Saad2011](https://www-users.cse.umn.edu/~saad/eig_book_2ndEd.pdf).
At each step, the running estimate for the result is …

Lanczos-based `spectrum` method

---

CHANGELOG.md
src/qobj/quantum_object_base.jl
test/core-test/quantum_objects.jl

Implement `Base.copy` for `AbstractQuantumObject`

---

CHANGELOG.md
docs/src/users_guide/plotting_the_bloch_sphere.md
ext/QuantumToolboxMakieExt.jl
src/visualization.jl
test/ext-test/cpu/makie/makie_ext.jl

use `LScene` instead of `Axis3` for Bloch Sphere rendering, in order to have more freedom.

Use LScene instead of Axis3 for Bloch Sphere

---

CHANGELOG.md
docs/src/users_guide/plotting_the_bloch_sphere.md
ext/QuantumToolboxMakieExt.jl
src/visualization.jl
test/ext-test/cpu/makie/makie_ext.jl

This PR does:
- set default font size to `20`
- add kwargs `kind` for `add_states!` (same as `qutip`)
- improve the handling of plot vector arrow length.
- fix all incorrect docstrings
- merge the codes in `_draw_reference_circles!` and `_draw_axes!` into `_draw_bloch_sphere!`
- remove redundant wire frame drawings

Fix `Bloch` docstrings and improve visualization of the sphere

---

src/qobj/synonyms.jl
src/time_evolution/time_evolution.jl

fix typos in doc strings

---

src/QuantumToolbox.jl
src/qobj/dimensions.jl
src/qobj/energy_restricted.jl
src/qobj/space.jl
test/core-test/enr_state_operator.jl

First try of ENR implementation

---

CHANGELOG.md
src/spectrum.jl
test/core-test/correlations_and_spectrum.jl

Check for breakdown of orthogonality and orthogonal initial vectors in the `Lanczos` solver.
Fixes #501.

Check for orthogonality breakdown in `Lanczos`

---

CHANGELOG.md
docs/src/resources/api.md
docs/src/users_guide/QuantumObject/QuantumObject.md
src/QuantumToolbox.jl
src/negativity.jl
src/qobj/arithmetic_and_attributes.jl
src/qobj/dimensions.jl
src/qobj/energy_restricted.jl
src/qobj/quantum_object_base.jl
src/qobj/space.jl
test/core-test/enr_state_operator.jl

Add functionalities for ENR space, as [QuTiP](https://github.com/qutip/qutip/blob/9f6393cb96bfc76d4a603b1e0aacbea77bde7a55/qutip/core/energy_restricted.py).
- `enr_identity`
- `enr_fock`
- `enr_destroy`
- `enr_thermal_dm`

Excitation number restricted (`ENR`) state space implementation 

---

test/core-test/time_evolution.jl

Although there is a lot of lines changing in this PR. But basically it's just re-organizing the structure of time evolution runtests.
By using the `@testmodule` macro (see [here](https://www.julia-vscode.org/docs/stable/userguide/testitems/#Test-modules) for more details), we can divide the current time evolution tests into individual `@testitems`.
This advantages runtests on both local VS-code extension and CI pipeline: …

separate time evolution tests into individual `@testitems`

---

CHANGELOG.md
docs/src/users_guide/settings.md
docs/src/users_guide/time_evolution/brmesolve.md
src/time_evolution/brmesolve.jl
test/core-test/brmesolve.jl

The current implementation of the `bloch_redfield_tensor` function rotates the basis at the end. This is very inefficient as the rotation superoperator is a large dense matrix.
In this PR, I rotate the basis (if asked) directly during the computation. Avoiding to define the rotation operator. This surely improves the `fock_basis=false` case, and partially improves the true case.

Improve efficiency of generation of Bloch-Redfield tensor and fix documentation typos

---

CHANGELOG.md
docs/src/users_guide/plotting_the_bloch_sphere.md
ext/QuantumToolboxMakieExt.jl
test/ext-test/cpu/makie/makie_ext.jl

As title.
In this PR, we allow the keyword argument `location` of `render` function can be given in the either type: 
- `Nothing` (default): Create a new `Figure` and plot the `Bloch` sphere.
- `GridPosition`: Plot the `Bloch` sphere in the specified location of the plot in the layout.
- `LScene`: Update the existing Bloch sphere using new data and settings in `b::Bloch` without creating new `Figure` and `LScene` …

Improve Bloch sphere rendering for animation

---

src/time_evolution/mcsolve.jl
src/time_evolution/mesolve.jl
src/time_evolution/sesolve.jl
src/time_evolution/smesolve.jl
src/time_evolution/ssesolve.jl

This PR fixes the recent errors on autodiff with Zygote.jl.

Fix Zygote autodiff errors

---

CHANGELOG.md
src/steadystate.jl
test/core-test/steady_state.jl
test/ext-test/cpu/autodiff/autodiff.jl

Add `QobjEvo` support for `SteadyStateODESolver`

---

CHANGELOG.md
src/steadystate.jl

This PR introduces two new fields
- `terminate_reltol = 1e-5`
- `terminate_abstol = 1e-7`
for `SteadyStateODESolver`, in order to separate from the tolerances which pass to `mesolve` through `steadystate(...; kwargs...)`.
Also, this PR fixes several `kwargs` handling for `SteadyStateODESolver` before passing to `mesolve`.

Fix keyword argument handling for `SteadyStateODESolver`

---

ext/QuantumToolboxMakieExt.jl

Try to fix the following warning message from `Makie` while rendering `Bloch` sphere vectors:
```
Arrows3D{Tuple{Vector{GeometryBasics.Point{3, Float32}}, Vector{Vector{Float64}}}} is not supported by cairo right now
```
Also, remove some redundant imports from our `QuantumToolboxMakieExt`.

Fix `Makie` warning message

---

.github/workflows/Code-Quality.yml
src/qobj/boolean_functions.jl
src/visualization.jl

Try to see if the code quality can be run on `Julia 1`

Run code-quality CI also on `Julia 1`

---

CHANGELOG.md
src/versioninfo.jl
test/core-test/utilities.jl

Fix incorrect bibtex in `cite()`: 
```
publisher = {{Verein zur F{\\"{o}}rderung ... }},
```
(need double `\` in `String` to show single `\` in output).
Furthermore, this PR also remove the redundant line break at the end.

Fix `cite()` bibtex output
